[package]
name = "gen"
description = "command-line utility for generating strings matching a pattern"
authors = ["rakete"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
nom = "7.1.3"
rand = "0.8.5"
